"""Pipeline orchestration."""

from .contracts import (
    ArtifactRef,
    BenchmarkEvaluationConfig,
    CloudMetrics,
    DatasetSourceSpec,
    DenseArtifacts,
    DenseConfig,
    EfficiencyMetrics,
    FramePacket,
    LiveSourceSpec,
    PipelineMode,
    ReferenceArtifacts,
    ReferenceConfig,
    RunPlan,
    RunPlanStage,
    RunPlanStageId,
    RunRequest,
    RunSummary,
    SequenceManifest,
    StageExecutionStatus,
    StageManifest,
    TrackingArtifacts,
    TrackingConfig,
    TrajectoryMetrics,
    VideoSourceSpec,
)
from .interfaces import (
    CloudEvaluator,
    DenseBackend,
    OfflineTrackerBackend,
    ReferenceBuilder,
    StreamingTrackerBackend,
    TrackingUpdate,
    TrajectoryEvaluator,
)
from .services import PipelinePlannerService
from .workspace import CaptureManifest, FrameSample, PreparedInput

__all__ = [
    "ArtifactRef",
    "BenchmarkEvaluationConfig",
    "CaptureManifest",
    "CloudEvaluator",
    "CloudMetrics",
    "DatasetSourceSpec",
    "DenseArtifacts",
    "DenseBackend",
    "DenseConfig",
    "EfficiencyMetrics",
    "FramePacket",
    "FrameSample",
    "LiveSourceSpec",
    "OfflineTrackerBackend",
    "PipelineMode",
    "PipelinePlannerService",
    "PreparedInput",
    "ReferenceArtifacts",
    "ReferenceBuilder",
    "ReferenceConfig",
    "RunPlan",
    "RunPlanStage",
    "RunPlanStageId",
    "RunRequest",
    "RunSummary",
    "SequenceManifest",
    "StageExecutionStatus",
    "StageManifest",
    "StreamingTrackerBackend",
    "TrackingArtifacts",
    "TrackingConfig",
    "TrackingUpdate",
    "TrajectoryEvaluator",
    "TrajectoryMetrics",
    "VideoSourceSpec",
]
